export const BAD_REQUEST = 'BAD_REQUEST';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const NOT_FOUND = 'NOT_FOUND';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const VALIDATION = 'VALIDATION';
export const FORBIDDEN = 'FORBIDDEN';
