version: '3.8'

name: 'nestjs-boilerplate'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nestjs-boilerplate
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - .data:/var/lib/postgresql/data